PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: attributeinfo
CREATE TABLE attributeinfo (
    AttributeInfoID INTEGER      PRIMARY KEY AUTOINCREMENT
                                 UNIQUE
                                 NOT NULL,
    AttributeAbilID VARCHAR (4)  NOT NULL,
    AttributeName   VARCHAR (60) NOT NULL
);

INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (47, 'A0GO', 'Sphere Boundary');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (48, 'A0GP', 'Fierce Tiger Forcibly Climbs a Mountain');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (49, 'A0GF', 'Circulatory Shock');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (51, 'A0GG', 'Double Class');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (52, 'A077', 'Improved Territory');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (53, 'A082', 'Divine Language');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (54, 'A07R', 'Improved Hecatic Graea');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (55, 'A07H', 'Improved Aegis');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (56, 'A07B', 'Improved Gae Bolg');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (57, 'A07L', 'Flying Spear of Barbed Death');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (58, 'A07V', 'Spear of Death');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (59, 'A0GL', 'Improved Runes');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (60, 'A071', 'Improved Battle Continuation');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (61, 'A08K', 'Protection of Fairies');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (62, 'A08M', 'Honor of the Shining Lake');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (64, 'A08J', 'Eternal Arms Mastership');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (65, 'A08L', 'Improved Arondight');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (66, 'A081', 'Phantom Attack');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (67, 'A0H0', 'Delusional Illusion');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (68, 'A07Q', 'Zabaniya');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (69, 'A07G', 'Protection from Wind');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (70, 'A07A', 'Riding');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (71, 'A07K', 'Seal');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (72, 'A07U', 'Monstrous Strength');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (73, 'A070', 'Improved Mystic Eyes');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (74, 'A074', 'Improved Clairvoyance');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (75, 'A07E', 'Hrunting');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (76, 'A07Y', 'Improved Tracing');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (77, 'A07I', 'Mana Blast');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (78, 'A078', 'Improved Mana Shroud');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (79, 'A083', 'Black Light - Dark Excalibur');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (80, 'A0BV', 'Improved Ferocity');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (81, 'A0AC', 'Blooming of Yellow-Red Rose');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (82, 'A0AE', 'Double Spear');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (83, 'A073', 'Improved Excalibur');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (84, 'A0FZ', 'Strike Air');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (85, 'A07D', 'Improved Instincts');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (86, 'A0K9', 'Dragon Skillet');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (87, 'A0KC', 'Rainbow Plains and the Maze of Mirrors');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (88, 'A0KD', 'The King of Black and White Checkerboard');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (89, 'A0D4', '');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (90, 'A0D3', 'Improved Black Magic');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (91, 'A0CY', 'Improved Demonic Creature of the Ocean Depths');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (92, 'A0CV', 'Contagion');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (93, 'A0J2', 'Key to the Theater');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (94, 'A0IW', 'Embryonic Flame');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (95, 'A0IX', 'Imperial Privilege');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (96, 'A0J0', 'Thrice, Though I Welcome the Setting Sun');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (97, 'A0JS', 'Improved Vasavi Shakti');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (98, 'A0JQ', 'Improved Divinity');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (99, 'A0JR', 'Improved Brahmastra');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (100, 'A0I9', 'Sacramentum of Druid');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (101, 'A0I8', 'Sherwood Forest');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (102, 'A0I6', 'One Drop of a Viper');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (103, 'A0I7', 'Poisoned Arrow');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (104, 'A07N', 'Knighthood');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (105, 'A07X', 'Improved Charisma');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (106, 'A06F', 'Improved Ionion Hetairoi');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (107, 'A053', 'Improved Charisma');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (108, 'A046', 'Improved Military Tactics');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (109, 'A0BP', 'Eye for Art');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (110, 'A07Z', 'Quick Draw');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (111, 'A07P', 'Eye of Serenity');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (112, 'A09O', 'Monohoshi Zao');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (113, 'A075', 'Eye of the Mind');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (114, 'A06C', 'Nightmare');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (115, 'A060', 'Blood Metastasis');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (116, 'A0BQ', 'Avenger of Blood');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (117, 'A066', 'Tawrich and Zarich');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (118, 'A0BM', 'Spirit Orb');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (119, 'A0C8', 'Witchcraft');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (120, 'A0BZ', 'Cursed Charms');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (122, 'A0C1', 'Improved Territory');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (123, 'A0KA', 'Ackroyd in Celluloid');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (124, 'A0JT', 'Prana Burst');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (125, 'A00N', 'Kansho Bakuya Overedge');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (126, 'A0I5', 'The Faceless King');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (127, 'A05N', 'Wheel of Gordias');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (128, 'A05F', 'Improved Spatha');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (129, 'A000', 'Improved Divinity');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (130, 'A07J', 'Improved Sword Rain');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (131, 'A07T', 'The Star of Creation that Split Heaven and Earth');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (132, 'A0ED', 'Sword of Victory');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (133, 'A0EC', 'Numeral of the Saint');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (134, 'A072', 'Sacred Mirror');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (135, 'A07F', 'Ganryu - Shore Willow');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (136, 'A06S', 'Improved Golden Rule');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (137, 'A079', 'Power of Sumer');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (138, 'A07W', 'Reincarnation');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (139, 'A07M', 'God Hand');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (140, 'A0J1', 'Improved Fountain of the Saint');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (141, 'A0HF', 'Houtengageki');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (142, 'A0HL', 'Bravery');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (143, 'A0HK', 'Gate Halberd Shot');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (144, 'A0FE', 'Combustion Shot');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (145, 'A0FG', 'Improved Golden Hind');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (146, 'A0FH', 'Golden Rule : Pillage');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (147, 'A0EB', 'Knighthood');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (148, 'A0EA', 'Protection of the Fairies');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (149, 'A07C', 'Mad Enhancement');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (150, 'A0E9', 'Gwalhmai');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (151, 'A07O', 'Shroud of Martin');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (152, 'A0FD', 'Logbook');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (153, 'A0AT', 'Lord of Execution');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (154, 'A0B2', 'Rebellious Intent');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (155, 'A0AK', 'Innocent Monster');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (156, 'A0AS', 'Protection of the Faith');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (157, 'A0HE', 'Immortal Red Hare');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (158, 'A0HD', 'Red Hare');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (159, 'A0KB', 'Vorpal Blade');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (160, 'A0JP', 'Uncrowned Arms Mastership');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (161, 'A0AD', 'Minds Eye');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (162, 'A076', 'Improved Presence Concealment');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (163, 'A069', 'Curse of Blood');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (164, 'A08P', 'Improved Love Spot of Seduction');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (165, 'A0LD', 'Aspect of Dragon');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (166, 'A0LF', 'Double Class');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (167, 'A0LE', 'Innocent Monster');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (168, 'A0LC', 'Sadistic Charisma');
INSERT INTO attributeinfo (AttributeInfoID, AttributeAbilID, AttributeName) VALUES (169, 'A0LK', 'Torture Techniques');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
